name: Magento Coding Standard
on: [push, pull_request]
jobs:
  static:
    name: M2 Coding Standard
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Static analysis
        uses: extdn/github-actions-m2/magento-coding-standard@master
