name: PhpMD
on: [push, pull_request]
jobs:
  phpcs:
    name: PHP Mess Detector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: extdn/github-actions-m2/magento-mess-detector@master
