name: PhpStan
on: [push, pull_request]
jobs:
  phpcs:
    name: PhpStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: extdn/github-actions-m2/magento-phpstan@master
